language: java
sudo: false
jdk:
  - openjdk8
env:
  - CODACY_PROJECT_TOKEN=3b6d38f010804d1f8dd348c674db6ead
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn site
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b3bb74e8f738b9724be0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

